; Chinese UI overrides; technical error messages fall back to Default.isl.
[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=936
DialogFontName=Microsoft YaHei UI

[Messages]
SetupAppTitle=安装程序
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载程序
UninstallAppFullTitle=卸载 %1
InformationTitle=信息
ConfirmTitle=确认
ErrorTitle=错误
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonNo=否(&N)
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)...
ButtonWizardBrowse=浏览(&R)...
SelectLanguageTitle=选择安装语言
SelectLanguageLabel=请选择安装过程中使用的语言。
ClickNext=单击“下一步”继续，或单击“取消”退出安装。
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=这将在您的计算机上安装 [name/ver]。%n%n建议先关闭正在运行的 Voxenra，然后继续。
WizardInfoBefore=安装说明
InfoBeforeLabel=请在继续前阅读以下重要信息。
InfoBeforeClickLabel=准备好继续安装时，请单击“下一步”。
WizardSelectDir=选择安装位置
SelectDirDesc=您希望将 [name] 安装在哪里？
SelectDirLabel3=安装程序将把 [name] 安装到以下文件夹。
SelectDirBrowseLabel=单击“下一步”继续；如需选择其他位置，请单击“浏览”。
WizardSelectTasks=选择附加任务
SelectTasksDesc=您希望执行哪些附加任务？
SelectTasksLabel2=选择安装 [name] 时需要执行的附加任务，然后单击“下一步”。
WizardReady=准备安装
ReadyLabel1=安装程序已准备好在您的计算机上安装 [name]。
ReadyLabel2a=单击“安装”继续，或单击“上一步”检查安装设置。
ReadyMemoDir=安装位置：
ReadyMemoTasks=附加任务：
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候。
StatusExtractFiles=正在释放文件...
StatusCreateIcons=正在创建快捷方式...
StatusRunProgram=正在完成安装...
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=[name] 已安装到您的计算机。
FinishedLabel=安装已完成。您可以通过创建的快捷方式启动 [name]。
ClickFinish=单击“完成”退出安装向导。
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。现在退出将不会完成安装。%n%n确定退出吗？
ConfirmUninstall=确定要卸载 %1 及其安装组件吗？
UninstallStatusLabel=正在卸载 %1，请稍候。
UninstalledAll=%1 已成功从您的计算机中卸载。
